/**
 * Catalogue typé des capabilities — miroir exact de la table `public.capabilities`.
 *
 * Source de vérité côté client (auto-complétion des gardes `requireCapability`)
 * et référence des tests d'intégrité. Toute migration qui ajoute ou retire une
 * capability doit mettre ce fichier à jour : le test
 * `src/lib/capabilities/__tests__/matrix-integrity.test.ts` échoue sinon.
 */

export const CAPABILITY_CATALOG = {
  "actions": [
    { key: "action.create_devis", label: "Créer un devis" },
    { key: "action.sign_opportunite", label: "Signer une opportunité" },
    { key: "action.publish_plan_fab", label: "Publier un plan fab" },
    { key: "action.delete_plan_fab", label: "Supprimer un plan fab" },
    { key: "action.validate_hours", label: "Valider des heures" },
    { key: "action.create_contract", label: "Créer un contrat" },
    { key: "action.sign_contract", label: "Signer un contrat" },
    { key: "action.create_mission_pose", label: "Créer une mission de pose" },
    { key: "action.cancel_mission_pose", label: "Annuler une mission de pose" },
    { key: "action.export_data", label: "Exporter des données" },
    { key: "action.casting.manage", label: "Gérer le casting" },
    { key: "action.objet_equipe.manage", label: "Gérer l'équipe d'un objet" },
    { key: "action.upload_photo", label: "Uploader une photo" },
    { key: "action.delete_photo", label: "Supprimer une photo" },
    { key: "action.archive_affaire", label: "Archiver une affaire" },
    { key: "action.create_opportunite", label: "Créer une opportunité" },
    { key: "action.edit_opportunite", label: "Éditer une opportunité" },
    { key: "action.delete_opportunite", label: "Supprimer une opportunité" },
  ],
  "admin": [
    { key: "admin.feature_flags", label: "Gérer les feature flags" },
    { key: "admin.feature_flags.manage", label: "Modifier les feature flags" },
    { key: "admin.audit", label: "Voir audit + incidents auth" },
    { key: "admin.permissions", label: "Gérer les capabilities" },
    { key: "admin.permissions.manage", label: "Modifier la matrice de permissions" },
    { key: "admin.email_preview.view", label: "Email preview" },
    { key: "admin.feedback.view", label: "Feedbacks" },
    { key: "admin.roadmap.manage", label: "Gérer la roadmap" },
  ],
  "affaires": [
    { key: "affaires.view", label: "Voir toutes les affaires" },
    { key: "affaires.edit", label: "Modifier une affaire" },
    { key: "affaires.delete", label: "Supprimer une affaire" },
    { key: "affaires.documents.upload", label: "Téléverser documents affaire" },
    { key: "affaire.equipe.view", label: "Voir onglet Équipe d'une affaire" },
    { key: "affaire.kpi.view", label: "Voir le bandeau KPI 360°" },
    { key: "affaire.team.manage", label: "Gérer le casting d'affaire" },
    { key: "affaire.documents.delete", label: "Supprimer documents affaire" },
  ],
  "candidatures": [
    { key: "candidatures.view", label: "Candidatures : voir" },
    { key: "candidatures.manage", label: "Candidatures : gérer" },
  ],
  "casting": [
    { key: "casting.view_phase_commercial", label: "Voir casting — phase commercial" },
    { key: "casting.view_phase_fabrication", label: "Voir casting — phase fabrication" },
    { key: "casting.view_phase_logistique", label: "Voir casting — phase logistique" },
    { key: "casting.view_phase_montage", label: "Voir casting — phase montage" },
    { key: "casting.view_phase_demontage", label: "Voir casting — phase démontage" },
    { key: "casting.edit_phase_commercial", label: "Éditer casting — phase commercial" },
    { key: "casting.edit_phase_fabrication", label: "Éditer casting — phase fabrication" },
    { key: "casting.edit_phase_logistique", label: "Éditer casting — phase logistique" },
    { key: "casting.edit_phase_montage", label: "Éditer casting — phase montage" },
    { key: "casting.edit_phase_demontage", label: "Éditer casting — phase démontage" },
  ],
  "clients": [
    { key: "clients.view", label: "Voir les clients" },
    { key: "clients.manage", label: "Gérer les clients" },
    { key: "clients.update", label: "Modifier les fiches client" },
    { key: "clients.merge", label: "Fusionner des clients" },
  ],
  "dashboard": [
    { key: "dashboard.team.view", label: "Widgets équipe (dashboard)" },
    { key: "dashboard.commerce.view", label: "Widget commerce (dashboard)" },
  ],
  "data": [
    { key: "data.margins", label: "Marges & budget" },
    { key: "data.salaries", label: "Salaires & taux" },
    { key: "data.client_contacts", label: "Contacts client" },
    { key: "data.employee_rh", label: "Fiches RH employés" },
    { key: "data.journal_client", label: "Journal client" },
    { key: "data.audit_logs", label: "Journaux d'audit" },
    { key: "opportunites.read.mine", label: "Voir mes opportunités" },
  ],
  "devis": [
    { key: "devis.view", label: "Voir les devis" },
    { key: "devis.import", label: "Importer un devis" },
    { key: "devis.delete", label: "Supprimer un devis" },
  ],
  "fabrication": [
    { key: "objet.view", label: "Voir une fiche objet" },
    { key: "objet.edit", label: "Modifier une fiche objet" },
    { key: "objet.photo.delete", label: "Supprimer une photo d'objet" },
    { key: "objet.team.manage", label: "Gérer l'équipe d'un objet" },
    { key: "objet.photo.upload", label: "Téléverser une photo d'objet" },
    { key: "fabrication.etape.admin_override", label: "Forcer édition étape fab" },
  ],
  "feedback": [
    { key: "feedback.create", label: "Soumettre un feedback" },
  ],
  "flotte": [
    { key: "flotte.trajet.delete", label: "Supprimer un trajet flotte" },
  ],
  "heures": [
    { key: "heures.export.admin_formats", label: "Exports heures formats admin" },
    { key: "heures.personnelles.saisir", label: "Saisir ses propres heures" },
    { key: "heures.equipe.saisir", label: "Saisir pour son équipe" },
    { key: "heures.valider", label: "Valider les heures" },
    { key: "heures.audit", label: "Auditer les heures" },
  ],
  "inbox": [
    { key: "inbox.mission_pose", label: "Missions de pose" },
    { key: "inbox.validation_heures", label: "Validation des heures" },
    { key: "inbox.be_attente", label: "BE en attente" },
    { key: "inbox.devis_brouillon", label: "Devis brouillons" },
    { key: "inbox.opp_action", label: "Opportunités à actionner" },
    { key: "inbox.echantillons", label: "Échantillons à traiter" },
    { key: "inbox.plan_lacune", label: "Lacunes de planning" },
    { key: "inbox.heures_saisir", label: "Heures à saisir" },
    { key: "inbox.rh_contrats", label: "Contrats RH à traiter" },
    { key: "inbox.alerte.sous_dim", label: "Alerte équipe sous-dimensionnée" },
    { key: "inbox.alertes_equipe", label: "Alertes équipe" },
    { key: "inbox.alerte.depassement", label: "Alerte dépassement heures" },
    { key: "inbox.alerte.cumul_100", label: "Alerte cumul personne ≥ 100%" },
    { key: "inbox.atelier_rappel", label: "Rappels atelier (plan non publié)" },
    { key: "inbox.alerte.hors_equipe", label: "Alerte saisie hors équipe" },
    { key: "inbox.dismiss", label: "Masquer un item inbox" },
  ],
  "inbox_smart": [
    { key: "inbox_smart.view", label: "Inbox Smart : voir" },
  ],
  "mes": [
    { key: "mes_missions.view", label: "Voir les missions" },
    { key: "mes_chantiers.view", label: "Voir les chantiers" },
    { key: "mes_heures.view", label: "Voir les heures" },
    { key: "mes_contrats.view", label: "Voir les contrats" },
    { key: "mes_propositions.view", label: "Voir les propositions" },
    { key: "mes_swaps.view", label: "Voir les échanges" },
  ],
  "mobile": [
    { key: "mobile.mes_missions", label: "Mobile — Mes missions" },
    { key: "mobile.equipe_chantiers", label: "Mobile — Équipe & chantiers" },
    { key: "mobile.fabrication_atelier", label: "Mobile — Atelier" },
    { key: "mobile.staffer_rapide", label: "Mobile — Staffer rapide" },
    { key: "mobile.signaler_probleme", label: "Mobile — Signaler un problème" },
  ],
  "mon-poste": [
    { key: "mon-poste.aujourdhui.view", label: "Voir \"Aujourd'hui\"" },
    { key: "mon-poste.mission.record_event", label: "Enregistrer un événement mission" },
    { key: "mon-poste.mission.signal_probleme", label: "Signaler un problème mission" },
    { key: "mon-poste.semaine.view", label: "Voir \"Ma semaine\"" },
    { key: "mon-poste.mission.view", label: "Voir cartes mission" },
  ],
  "opportunites": [
    { key: "opportunites.read.all", label: "Lire toutes opportunités" },
  ],
  "parametres": [
    { key: "parametres.view", label: "Voir les paramètres" },
    { key: "parametres.edit", label: "Modifier les paramètres" },
    { key: "parametres.utilisateurs", label: "Gérer les utilisateurs" },
  ],
  "planning": [
    { key: "inbox.view", label: "Voir son inbox" },
    { key: "planning.view", label: "Voir le planning" },
    { key: "planning.edit", label: "Modifier le planning" },
  ],
  "rh": [
    { key: "rh.hub.view", label: "Accéder au hub RH" },
    { key: "employes.view", label: "Voir les employés" },
    { key: "employes.edit", label: "Modifier un employé" },
    { key: "employes.import", label: "Importer employés en lot" },
    { key: "contrats.view", label: "Voir les contrats" },
    { key: "contrats.view_own", label: "Voir ses propres contrats" },
    { key: "contrats.create", label: "Créer un contrat CDDU" },
    { key: "contrats.sign_employeur", label: "Signer côté employeur" },
    { key: "contrats.voir_taux", label: "Voir les taux horaires" },
  ],
  "sections": [
    { key: "section.inbox", label: "Aujourd'hui (inbox)" },
    { key: "section.ma_semaine", label: "Ma semaine" },
    { key: "section.tableau_de_bord", label: "Tableau de bord" },
    { key: "section.pipeline_opportunites", label: "Pipeline opportunités" },
    { key: "section.affaires", label: "Affaires" },
    { key: "section.devis", label: "Devis" },
    { key: "section.fabrication", label: "Fabrication" },
    { key: "section.planning_fab", label: "Planning fab" },
    { key: "section.planning_chantier_macro", label: "Planning chantier macro" },
    { key: "section.logistique", label: "Logistique" },
    { key: "section.equipes", label: "Équipes" },
    { key: "section.contrats_rh", label: "Contrats / RH" },
    { key: "section.admin", label: "Admin plateforme" },
  ],
  "staffing": [
    { key: "staffing.plan.create", label: "Créer un plan de staffing" },
    { key: "staffing.plan.publish", label: "Publier un plan" },
    { key: "staffing.plan.delete", label: "Supprimer un plan" },
    { key: "staffing.assignations.edit", label: "Éditer assignations engagées" },
    { key: "staffer.mobile.admin_override", label: "Override admin staffer mobile" },
  ],
} as const;

type Group = keyof typeof CAPABILITY_CATALOG;
export type CapabilityKey =
  (typeof CAPABILITY_CATALOG)[Group][number]["key"];

export const ALL_CAPABILITY_KEYS: readonly CapabilityKey[] = (
  Object.values(CAPABILITY_CATALOG).flat() as ReadonlyArray<{ key: CapabilityKey }>
).map((c) => c.key);

export const CAPABILITY_CATEGORY_LABELS: Record<Group, string> = {
  "actions": "Actions",
  "admin": "Administration",
  "affaires": "Affaires & objets",
  "candidatures": "Candidatures",
  "casting": "Casting par phase",
  "clients": "Clients",
  "dashboard": "Tableau de bord",
  "data": "Données sensibles",
  "devis": "Devis",
  "fabrication": "Fabrication",
  "feedback": "Feedback",
  "flotte": "Flotte",
  "heures": "Heures",
  "inbox": "Inbox (sources d'alerte)",
  "inbox_smart": "Inbox SMART",
  "mes": "Espace personnel",
  "mobile": "Mobile",
  "mon-poste": "Mon poste",
  "opportunites": "Opportunités",
  "parametres": "Paramètres",
  "planning": "Planning",
  "rh": "RH & contrats",
  "sections": "Sections (navigation)",
  "staffing": "Staffing",
};
