/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileAujourdhuiRouteImport } from './routes/mobile.aujourdhui'
import { Route as AppValidationHeuresRouteImport } from './routes/_app.validation-heures'
import { Route as AppPlanningRouteImport } from './routes/_app.planning'
import { Route as AppParametresRouteImport } from './routes/_app.parametres'
import { Route as AppExportRouteImport } from './routes/_app.export'
import { Route as AppEmployesRouteImport } from './routes/_app.employes'
import { Route as AppAffairesRouteImport } from './routes/_app.affaires'
import { Route as AppEmployesImportRouteImport } from './routes/_app.employes.import'
import { Route as AppDevisImportRouteImport } from './routes/_app.devis.import'
import { Route as AppAffairesAffaireIdRouteImport } from './routes/_app.affaires.$affaireId'
import { Route as AppAffairesAffaireIdIndexRouteImport } from './routes/_app.affaires.$affaireId.index'
import { Route as AppAffairesAffaireIdStaffingRouteImport } from './routes/_app.affaires.$affaireId.staffing'
import { Route as AppAffairesAffaireIdDevisRouteImport } from './routes/_app.affaires.$affaireId.devis'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAujourdhuiRoute = MobileAujourdhuiRouteImport.update({
  id: '/mobile/aujourdhui',
  path: '/mobile/aujourdhui',
  getParentRoute: () => rootRouteImport,
} as any)
const AppValidationHeuresRoute = AppValidationHeuresRouteImport.update({
  id: '/validation-heures',
  path: '/validation-heures',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanningRoute = AppPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployesRoute = AppEmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesRoute = AppAffairesRouteImport.update({
  id: '/affaires',
  path: '/affaires',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployesImportRoute = AppEmployesImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppEmployesRoute,
} as any)
const AppDevisImportRoute = AppDevisImportRouteImport.update({
  id: '/devis/import',
  path: '/devis/import',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesAffaireIdRoute = AppAffairesAffaireIdRouteImport.update({
  id: '/$affaireId',
  path: '/$affaireId',
  getParentRoute: () => AppAffairesRoute,
} as any)
const AppAffairesAffaireIdIndexRoute =
  AppAffairesAffaireIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAffairesAffaireIdRoute,
  } as any)
const AppAffairesAffaireIdStaffingRoute =
  AppAffairesAffaireIdStaffingRouteImport.update({
    id: '/staffing',
    path: '/staffing',
    getParentRoute: () => AppAffairesAffaireIdRoute,
  } as any)
const AppAffairesAffaireIdDevisRoute =
  AppAffairesAffaireIdDevisRouteImport.update({
    id: '/devis',
    path: '/devis',
    getParentRoute: () => AppAffairesAffaireIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/affaires': typeof AppAffairesRouteWithChildren
  '/employes': typeof AppEmployesRouteWithChildren
  '/export': typeof AppExportRoute
  '/parametres': typeof AppParametresRoute
  '/planning': typeof AppPlanningRoute
  '/validation-heures': typeof AppValidationHeuresRoute
  '/mobile/aujourdhui': typeof MobileAujourdhuiRoute
  '/affaires/$affaireId': typeof AppAffairesAffaireIdRouteWithChildren
  '/devis/import': typeof AppDevisImportRoute
  '/employes/import': typeof AppEmployesImportRoute
  '/affaires/$affaireId/devis': typeof AppAffairesAffaireIdDevisRoute
  '/affaires/$affaireId/staffing': typeof AppAffairesAffaireIdStaffingRoute
  '/affaires/$affaireId/': typeof AppAffairesAffaireIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/affaires': typeof AppAffairesRouteWithChildren
  '/employes': typeof AppEmployesRouteWithChildren
  '/export': typeof AppExportRoute
  '/parametres': typeof AppParametresRoute
  '/planning': typeof AppPlanningRoute
  '/validation-heures': typeof AppValidationHeuresRoute
  '/mobile/aujourdhui': typeof MobileAujourdhuiRoute
  '/devis/import': typeof AppDevisImportRoute
  '/employes/import': typeof AppEmployesImportRoute
  '/affaires/$affaireId/devis': typeof AppAffairesAffaireIdDevisRoute
  '/affaires/$affaireId/staffing': typeof AppAffairesAffaireIdStaffingRoute
  '/affaires/$affaireId': typeof AppAffairesAffaireIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/affaires': typeof AppAffairesRouteWithChildren
  '/_app/employes': typeof AppEmployesRouteWithChildren
  '/_app/export': typeof AppExportRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/planning': typeof AppPlanningRoute
  '/_app/validation-heures': typeof AppValidationHeuresRoute
  '/mobile/aujourdhui': typeof MobileAujourdhuiRoute
  '/_app/affaires/$affaireId': typeof AppAffairesAffaireIdRouteWithChildren
  '/_app/devis/import': typeof AppDevisImportRoute
  '/_app/employes/import': typeof AppEmployesImportRoute
  '/_app/affaires/$affaireId/devis': typeof AppAffairesAffaireIdDevisRoute
  '/_app/affaires/$affaireId/staffing': typeof AppAffairesAffaireIdStaffingRoute
  '/_app/affaires/$affaireId/': typeof AppAffairesAffaireIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/affaires'
    | '/employes'
    | '/export'
    | '/parametres'
    | '/planning'
    | '/validation-heures'
    | '/mobile/aujourdhui'
    | '/affaires/$affaireId'
    | '/devis/import'
    | '/employes/import'
    | '/affaires/$affaireId/devis'
    | '/affaires/$affaireId/staffing'
    | '/affaires/$affaireId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/affaires'
    | '/employes'
    | '/export'
    | '/parametres'
    | '/planning'
    | '/validation-heures'
    | '/mobile/aujourdhui'
    | '/devis/import'
    | '/employes/import'
    | '/affaires/$affaireId/devis'
    | '/affaires/$affaireId/staffing'
    | '/affaires/$affaireId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/affaires'
    | '/_app/employes'
    | '/_app/export'
    | '/_app/parametres'
    | '/_app/planning'
    | '/_app/validation-heures'
    | '/mobile/aujourdhui'
    | '/_app/affaires/$affaireId'
    | '/_app/devis/import'
    | '/_app/employes/import'
    | '/_app/affaires/$affaireId/devis'
    | '/_app/affaires/$affaireId/staffing'
    | '/_app/affaires/$affaireId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MobileAujourdhuiRoute: typeof MobileAujourdhuiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/aujourdhui': {
      id: '/mobile/aujourdhui'
      path: '/mobile/aujourdhui'
      fullPath: '/mobile/aujourdhui'
      preLoaderRoute: typeof MobileAujourdhuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/validation-heures': {
      id: '/_app/validation-heures'
      path: '/validation-heures'
      fullPath: '/validation-heures'
      preLoaderRoute: typeof AppValidationHeuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planning': {
      id: '/_app/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AppPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employes': {
      id: '/_app/employes'
      path: '/employes'
      fullPath: '/employes'
      preLoaderRoute: typeof AppEmployesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires': {
      id: '/_app/affaires'
      path: '/affaires'
      fullPath: '/affaires'
      preLoaderRoute: typeof AppAffairesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employes/import': {
      id: '/_app/employes/import'
      path: '/import'
      fullPath: '/employes/import'
      preLoaderRoute: typeof AppEmployesImportRouteImport
      parentRoute: typeof AppEmployesRoute
    }
    '/_app/devis/import': {
      id: '/_app/devis/import'
      path: '/devis/import'
      fullPath: '/devis/import'
      preLoaderRoute: typeof AppDevisImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires/$affaireId': {
      id: '/_app/affaires/$affaireId'
      path: '/$affaireId'
      fullPath: '/affaires/$affaireId'
      preLoaderRoute: typeof AppAffairesAffaireIdRouteImport
      parentRoute: typeof AppAffairesRoute
    }
    '/_app/affaires/$affaireId/': {
      id: '/_app/affaires/$affaireId/'
      path: '/'
      fullPath: '/affaires/$affaireId/'
      preLoaderRoute: typeof AppAffairesAffaireIdIndexRouteImport
      parentRoute: typeof AppAffairesAffaireIdRoute
    }
    '/_app/affaires/$affaireId/staffing': {
      id: '/_app/affaires/$affaireId/staffing'
      path: '/staffing'
      fullPath: '/affaires/$affaireId/staffing'
      preLoaderRoute: typeof AppAffairesAffaireIdStaffingRouteImport
      parentRoute: typeof AppAffairesAffaireIdRoute
    }
    '/_app/affaires/$affaireId/devis': {
      id: '/_app/affaires/$affaireId/devis'
      path: '/devis'
      fullPath: '/affaires/$affaireId/devis'
      preLoaderRoute: typeof AppAffairesAffaireIdDevisRouteImport
      parentRoute: typeof AppAffairesAffaireIdRoute
    }
  }
}

interface AppAffairesAffaireIdRouteChildren {
  AppAffairesAffaireIdDevisRoute: typeof AppAffairesAffaireIdDevisRoute
  AppAffairesAffaireIdStaffingRoute: typeof AppAffairesAffaireIdStaffingRoute
  AppAffairesAffaireIdIndexRoute: typeof AppAffairesAffaireIdIndexRoute
}

const AppAffairesAffaireIdRouteChildren: AppAffairesAffaireIdRouteChildren = {
  AppAffairesAffaireIdDevisRoute: AppAffairesAffaireIdDevisRoute,
  AppAffairesAffaireIdStaffingRoute: AppAffairesAffaireIdStaffingRoute,
  AppAffairesAffaireIdIndexRoute: AppAffairesAffaireIdIndexRoute,
}

const AppAffairesAffaireIdRouteWithChildren =
  AppAffairesAffaireIdRoute._addFileChildren(AppAffairesAffaireIdRouteChildren)

interface AppAffairesRouteChildren {
  AppAffairesAffaireIdRoute: typeof AppAffairesAffaireIdRouteWithChildren
}

const AppAffairesRouteChildren: AppAffairesRouteChildren = {
  AppAffairesAffaireIdRoute: AppAffairesAffaireIdRouteWithChildren,
}

const AppAffairesRouteWithChildren = AppAffairesRoute._addFileChildren(
  AppAffairesRouteChildren,
)

interface AppEmployesRouteChildren {
  AppEmployesImportRoute: typeof AppEmployesImportRoute
}

const AppEmployesRouteChildren: AppEmployesRouteChildren = {
  AppEmployesImportRoute: AppEmployesImportRoute,
}

const AppEmployesRouteWithChildren = AppEmployesRoute._addFileChildren(
  AppEmployesRouteChildren,
)

interface AppRouteChildren {
  AppAffairesRoute: typeof AppAffairesRouteWithChildren
  AppEmployesRoute: typeof AppEmployesRouteWithChildren
  AppExportRoute: typeof AppExportRoute
  AppParametresRoute: typeof AppParametresRoute
  AppPlanningRoute: typeof AppPlanningRoute
  AppValidationHeuresRoute: typeof AppValidationHeuresRoute
  AppDevisImportRoute: typeof AppDevisImportRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAffairesRoute: AppAffairesRouteWithChildren,
  AppEmployesRoute: AppEmployesRouteWithChildren,
  AppExportRoute: AppExportRoute,
  AppParametresRoute: AppParametresRoute,
  AppPlanningRoute: AppPlanningRoute,
  AppValidationHeuresRoute: AppValidationHeuresRoute,
  AppDevisImportRoute: AppDevisImportRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MobileAujourdhuiRoute: MobileAujourdhuiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
