/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileSwapsRouteImport } from './routes/mobile.swaps'
import { Route as MobilePropositionsRouteImport } from './routes/mobile.propositions'
import { Route as MobileProfilRouteImport } from './routes/mobile.profil'
import { Route as MobileMoisRouteImport } from './routes/mobile.mois'
import { Route as MobileHeuresRouteImport } from './routes/mobile.heures'
import { Route as MobileAujourdhuiRouteImport } from './routes/mobile.aujourdhui'
import { Route as MobileAbsencesRouteImport } from './routes/mobile.absences'
import { Route as AppValidationHeuresRouteImport } from './routes/_app.validation-heures'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppPlanningRouteImport } from './routes/_app.planning'
import { Route as AppMesSwapsRouteImport } from './routes/_app.mes-swaps'
import { Route as AppMesPropositionsRouteImport } from './routes/_app.mes-propositions'
import { Route as AppMesHeuresRouteImport } from './routes/_app.mes-heures'
import { Route as AppInterimairesRouteImport } from './routes/_app.interimaires'
import { Route as AppFlotteRouteImport } from './routes/_app.flotte'
import { Route as AppExportRouteImport } from './routes/_app.export'
import { Route as AppEmployesRouteImport } from './routes/_app.employes'
import { Route as AppDashboardEmployeRouteImport } from './routes/_app.dashboard-employe'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAbsencesRouteImport } from './routes/_app.absences'
import { Route as AppDevisIndexRouteImport } from './routes/_app.devis.index'
import { Route as AppAffairesIndexRouteImport } from './routes/_app.affaires.index'
import { Route as AppParametresUtilisateursRouteImport } from './routes/_app.parametres.utilisateurs'
import { Route as AppParametresMetiersRouteImport } from './routes/_app.parametres.metiers'
import { Route as AppExportDemandesDevisRouteImport } from './routes/_app.export.demandes-devis'
import { Route as AppEmployesImportRouteImport } from './routes/_app.employes.import'
import { Route as AppDevisImportRouteImport } from './routes/_app.devis.import'
import { Route as AppDevisHistoriqueRouteImport } from './routes/_app.devis.historique'
import { Route as AppAffairesAffaireIdRouteImport } from './routes/_app.affaires.$affaireId'
import { Route as AppAffairesAffaireIdIndexRouteImport } from './routes/_app.affaires.$affaireId.index'
import { Route as AppAffairesAffaireIdStaffingRouteImport } from './routes/_app.affaires.$affaireId.staffing'
import { Route as AppAffairesAffaireIdJournalRouteImport } from './routes/_app.affaires.$affaireId.journal'
import { Route as AppAffairesAffaireIdDevisRouteImport } from './routes/_app.affaires.$affaireId.devis'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileSwapsRoute = MobileSwapsRouteImport.update({
  id: '/mobile/swaps',
  path: '/mobile/swaps',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilePropositionsRoute = MobilePropositionsRouteImport.update({
  id: '/mobile/propositions',
  path: '/mobile/propositions',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileProfilRoute = MobileProfilRouteImport.update({
  id: '/mobile/profil',
  path: '/mobile/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileMoisRoute = MobileMoisRouteImport.update({
  id: '/mobile/mois',
  path: '/mobile/mois',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileHeuresRoute = MobileHeuresRouteImport.update({
  id: '/mobile/heures',
  path: '/mobile/heures',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAujourdhuiRoute = MobileAujourdhuiRouteImport.update({
  id: '/mobile/aujourdhui',
  path: '/mobile/aujourdhui',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAbsencesRoute = MobileAbsencesRouteImport.update({
  id: '/mobile/absences',
  path: '/mobile/absences',
  getParentRoute: () => rootRouteImport,
} as any)
const AppValidationHeuresRoute = AppValidationHeuresRouteImport.update({
  id: '/validation-heures',
  path: '/validation-heures',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanningRoute = AppPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AppRoute,
} as any)
const AppMesSwapsRoute = AppMesSwapsRouteImport.update({
  id: '/mes-swaps',
  path: '/mes-swaps',
  getParentRoute: () => AppRoute,
} as any)
const AppMesPropositionsRoute = AppMesPropositionsRouteImport.update({
  id: '/mes-propositions',
  path: '/mes-propositions',
  getParentRoute: () => AppRoute,
} as any)
const AppMesHeuresRoute = AppMesHeuresRouteImport.update({
  id: '/mes-heures',
  path: '/mes-heures',
  getParentRoute: () => AppRoute,
} as any)
const AppInterimairesRoute = AppInterimairesRouteImport.update({
  id: '/interimaires',
  path: '/interimaires',
  getParentRoute: () => AppRoute,
} as any)
const AppFlotteRoute = AppFlotteRouteImport.update({
  id: '/flotte',
  path: '/flotte',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployesRoute = AppEmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardEmployeRoute = AppDashboardEmployeRouteImport.update({
  id: '/dashboard-employe',
  path: '/dashboard-employe',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAbsencesRoute = AppAbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => AppRoute,
} as any)
const AppDevisIndexRoute = AppDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesIndexRoute = AppAffairesIndexRouteImport.update({
  id: '/affaires/',
  path: '/affaires/',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresUtilisateursRoute =
  AppParametresUtilisateursRouteImport.update({
    id: '/parametres/utilisateurs',
    path: '/parametres/utilisateurs',
    getParentRoute: () => AppRoute,
  } as any)
const AppParametresMetiersRoute = AppParametresMetiersRouteImport.update({
  id: '/parametres/metiers',
  path: '/parametres/metiers',
  getParentRoute: () => AppRoute,
} as any)
const AppExportDemandesDevisRoute = AppExportDemandesDevisRouteImport.update({
  id: '/demandes-devis',
  path: '/demandes-devis',
  getParentRoute: () => AppExportRoute,
} as any)
const AppEmployesImportRoute = AppEmployesImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppEmployesRoute,
} as any)
const AppDevisImportRoute = AppDevisImportRouteImport.update({
  id: '/devis/import',
  path: '/devis/import',
  getParentRoute: () => AppRoute,
} as any)
const AppDevisHistoriqueRoute = AppDevisHistoriqueRouteImport.update({
  id: '/devis/historique',
  path: '/devis/historique',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesAffaireIdRoute = AppAffairesAffaireIdRouteImport.update({
  id: '/affaires/$affaireId',
  path: '/affaires/$affaireId',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesAffaireIdIndexRoute =
  AppAffairesAffaireIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAffairesAffaireIdRoute,
  } as any)
const AppAffairesAffaireIdStaffingRoute =
  AppAffairesAffaireIdStaffingRouteImport.update({
    id: '/staffing',
    path: '/staffing',
    getParentRoute: () => AppAffairesAffaireIdRoute,
  } as any)
const AppAffairesAffaireIdJournalRoute =
  AppAffairesAffaireIdJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AppAffairesAffaireIdRoute,
  } as any)
const AppAffairesAffaireIdDevisRoute =
  AppAffairesAffaireIdDevisRouteImport.update({
    id: '/devis',
    path: '/devis',
    getParentRoute: () => AppAffairesAffaireIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/absences': typeof AppAbsencesRoute
  '/dashboard': typeof AppDashboardRoute
  '/dashboard-employe': typeof AppDashboardEmployeRoute
  '/employes': typeof AppEmployesRouteWithChildren
  '/export': typeof AppExportRouteWithChildren
  '/flotte': typeof AppFlotteRoute
  '/interimaires': typeof AppInterimairesRoute
  '/mes-heures': typeof AppMesHeuresRoute
  '/mes-propositions': typeof AppMesPropositionsRoute
  '/mes-swaps': typeof AppMesSwapsRoute
  '/planning': typeof AppPlanningRoute
  '/roadmap': typeof AppRoadmapRoute
  '/validation-heures': typeof AppValidationHeuresRoute
  '/mobile/absences': typeof MobileAbsencesRoute
  '/mobile/aujourdhui': typeof MobileAujourdhuiRoute
  '/mobile/heures': typeof MobileHeuresRoute
  '/mobile/mois': typeof MobileMoisRoute
  '/mobile/profil': typeof MobileProfilRoute
  '/mobile/propositions': typeof MobilePropositionsRoute
  '/mobile/swaps': typeof MobileSwapsRoute
  '/affaires/$affaireId': typeof AppAffairesAffaireIdRouteWithChildren
  '/devis/historique': typeof AppDevisHistoriqueRoute
  '/devis/import': typeof AppDevisImportRoute
  '/employes/import': typeof AppEmployesImportRoute
  '/export/demandes-devis': typeof AppExportDemandesDevisRoute
  '/parametres/metiers': typeof AppParametresMetiersRoute
  '/parametres/utilisateurs': typeof AppParametresUtilisateursRoute
  '/affaires/': typeof AppAffairesIndexRoute
  '/devis/': typeof AppDevisIndexRoute
  '/affaires/$affaireId/devis': typeof AppAffairesAffaireIdDevisRoute
  '/affaires/$affaireId/journal': typeof AppAffairesAffaireIdJournalRoute
  '/affaires/$affaireId/staffing': typeof AppAffairesAffaireIdStaffingRoute
  '/affaires/$affaireId/': typeof AppAffairesAffaireIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/absences': typeof AppAbsencesRoute
  '/dashboard': typeof AppDashboardRoute
  '/dashboard-employe': typeof AppDashboardEmployeRoute
  '/employes': typeof AppEmployesRouteWithChildren
  '/export': typeof AppExportRouteWithChildren
  '/flotte': typeof AppFlotteRoute
  '/interimaires': typeof AppInterimairesRoute
  '/mes-heures': typeof AppMesHeuresRoute
  '/mes-propositions': typeof AppMesPropositionsRoute
  '/mes-swaps': typeof AppMesSwapsRoute
  '/planning': typeof AppPlanningRoute
  '/roadmap': typeof AppRoadmapRoute
  '/validation-heures': typeof AppValidationHeuresRoute
  '/mobile/absences': typeof MobileAbsencesRoute
  '/mobile/aujourdhui': typeof MobileAujourdhuiRoute
  '/mobile/heures': typeof MobileHeuresRoute
  '/mobile/mois': typeof MobileMoisRoute
  '/mobile/profil': typeof MobileProfilRoute
  '/mobile/propositions': typeof MobilePropositionsRoute
  '/mobile/swaps': typeof MobileSwapsRoute
  '/devis/historique': typeof AppDevisHistoriqueRoute
  '/devis/import': typeof AppDevisImportRoute
  '/employes/import': typeof AppEmployesImportRoute
  '/export/demandes-devis': typeof AppExportDemandesDevisRoute
  '/parametres/metiers': typeof AppParametresMetiersRoute
  '/parametres/utilisateurs': typeof AppParametresUtilisateursRoute
  '/affaires': typeof AppAffairesIndexRoute
  '/devis': typeof AppDevisIndexRoute
  '/affaires/$affaireId/devis': typeof AppAffairesAffaireIdDevisRoute
  '/affaires/$affaireId/journal': typeof AppAffairesAffaireIdJournalRoute
  '/affaires/$affaireId/staffing': typeof AppAffairesAffaireIdStaffingRoute
  '/affaires/$affaireId': typeof AppAffairesAffaireIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/absences': typeof AppAbsencesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dashboard-employe': typeof AppDashboardEmployeRoute
  '/_app/employes': typeof AppEmployesRouteWithChildren
  '/_app/export': typeof AppExportRouteWithChildren
  '/_app/flotte': typeof AppFlotteRoute
  '/_app/interimaires': typeof AppInterimairesRoute
  '/_app/mes-heures': typeof AppMesHeuresRoute
  '/_app/mes-propositions': typeof AppMesPropositionsRoute
  '/_app/mes-swaps': typeof AppMesSwapsRoute
  '/_app/planning': typeof AppPlanningRoute
  '/_app/roadmap': typeof AppRoadmapRoute
  '/_app/validation-heures': typeof AppValidationHeuresRoute
  '/mobile/absences': typeof MobileAbsencesRoute
  '/mobile/aujourdhui': typeof MobileAujourdhuiRoute
  '/mobile/heures': typeof MobileHeuresRoute
  '/mobile/mois': typeof MobileMoisRoute
  '/mobile/profil': typeof MobileProfilRoute
  '/mobile/propositions': typeof MobilePropositionsRoute
  '/mobile/swaps': typeof MobileSwapsRoute
  '/_app/affaires/$affaireId': typeof AppAffairesAffaireIdRouteWithChildren
  '/_app/devis/historique': typeof AppDevisHistoriqueRoute
  '/_app/devis/import': typeof AppDevisImportRoute
  '/_app/employes/import': typeof AppEmployesImportRoute
  '/_app/export/demandes-devis': typeof AppExportDemandesDevisRoute
  '/_app/parametres/metiers': typeof AppParametresMetiersRoute
  '/_app/parametres/utilisateurs': typeof AppParametresUtilisateursRoute
  '/_app/affaires/': typeof AppAffairesIndexRoute
  '/_app/devis/': typeof AppDevisIndexRoute
  '/_app/affaires/$affaireId/devis': typeof AppAffairesAffaireIdDevisRoute
  '/_app/affaires/$affaireId/journal': typeof AppAffairesAffaireIdJournalRoute
  '/_app/affaires/$affaireId/staffing': typeof AppAffairesAffaireIdStaffingRoute
  '/_app/affaires/$affaireId/': typeof AppAffairesAffaireIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/absences'
    | '/dashboard'
    | '/dashboard-employe'
    | '/employes'
    | '/export'
    | '/flotte'
    | '/interimaires'
    | '/mes-heures'
    | '/mes-propositions'
    | '/mes-swaps'
    | '/planning'
    | '/roadmap'
    | '/validation-heures'
    | '/mobile/absences'
    | '/mobile/aujourdhui'
    | '/mobile/heures'
    | '/mobile/mois'
    | '/mobile/profil'
    | '/mobile/propositions'
    | '/mobile/swaps'
    | '/affaires/$affaireId'
    | '/devis/historique'
    | '/devis/import'
    | '/employes/import'
    | '/export/demandes-devis'
    | '/parametres/metiers'
    | '/parametres/utilisateurs'
    | '/affaires/'
    | '/devis/'
    | '/affaires/$affaireId/devis'
    | '/affaires/$affaireId/journal'
    | '/affaires/$affaireId/staffing'
    | '/affaires/$affaireId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/absences'
    | '/dashboard'
    | '/dashboard-employe'
    | '/employes'
    | '/export'
    | '/flotte'
    | '/interimaires'
    | '/mes-heures'
    | '/mes-propositions'
    | '/mes-swaps'
    | '/planning'
    | '/roadmap'
    | '/validation-heures'
    | '/mobile/absences'
    | '/mobile/aujourdhui'
    | '/mobile/heures'
    | '/mobile/mois'
    | '/mobile/profil'
    | '/mobile/propositions'
    | '/mobile/swaps'
    | '/devis/historique'
    | '/devis/import'
    | '/employes/import'
    | '/export/demandes-devis'
    | '/parametres/metiers'
    | '/parametres/utilisateurs'
    | '/affaires'
    | '/devis'
    | '/affaires/$affaireId/devis'
    | '/affaires/$affaireId/journal'
    | '/affaires/$affaireId/staffing'
    | '/affaires/$affaireId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/absences'
    | '/_app/dashboard'
    | '/_app/dashboard-employe'
    | '/_app/employes'
    | '/_app/export'
    | '/_app/flotte'
    | '/_app/interimaires'
    | '/_app/mes-heures'
    | '/_app/mes-propositions'
    | '/_app/mes-swaps'
    | '/_app/planning'
    | '/_app/roadmap'
    | '/_app/validation-heures'
    | '/mobile/absences'
    | '/mobile/aujourdhui'
    | '/mobile/heures'
    | '/mobile/mois'
    | '/mobile/profil'
    | '/mobile/propositions'
    | '/mobile/swaps'
    | '/_app/affaires/$affaireId'
    | '/_app/devis/historique'
    | '/_app/devis/import'
    | '/_app/employes/import'
    | '/_app/export/demandes-devis'
    | '/_app/parametres/metiers'
    | '/_app/parametres/utilisateurs'
    | '/_app/affaires/'
    | '/_app/devis/'
    | '/_app/affaires/$affaireId/devis'
    | '/_app/affaires/$affaireId/journal'
    | '/_app/affaires/$affaireId/staffing'
    | '/_app/affaires/$affaireId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MobileAbsencesRoute: typeof MobileAbsencesRoute
  MobileAujourdhuiRoute: typeof MobileAujourdhuiRoute
  MobileHeuresRoute: typeof MobileHeuresRoute
  MobileMoisRoute: typeof MobileMoisRoute
  MobileProfilRoute: typeof MobileProfilRoute
  MobilePropositionsRoute: typeof MobilePropositionsRoute
  MobileSwapsRoute: typeof MobileSwapsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/swaps': {
      id: '/mobile/swaps'
      path: '/mobile/swaps'
      fullPath: '/mobile/swaps'
      preLoaderRoute: typeof MobileSwapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/propositions': {
      id: '/mobile/propositions'
      path: '/mobile/propositions'
      fullPath: '/mobile/propositions'
      preLoaderRoute: typeof MobilePropositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/profil': {
      id: '/mobile/profil'
      path: '/mobile/profil'
      fullPath: '/mobile/profil'
      preLoaderRoute: typeof MobileProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/mois': {
      id: '/mobile/mois'
      path: '/mobile/mois'
      fullPath: '/mobile/mois'
      preLoaderRoute: typeof MobileMoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/heures': {
      id: '/mobile/heures'
      path: '/mobile/heures'
      fullPath: '/mobile/heures'
      preLoaderRoute: typeof MobileHeuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/aujourdhui': {
      id: '/mobile/aujourdhui'
      path: '/mobile/aujourdhui'
      fullPath: '/mobile/aujourdhui'
      preLoaderRoute: typeof MobileAujourdhuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/absences': {
      id: '/mobile/absences'
      path: '/mobile/absences'
      fullPath: '/mobile/absences'
      preLoaderRoute: typeof MobileAbsencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/validation-heures': {
      id: '/_app/validation-heures'
      path: '/validation-heures'
      fullPath: '/validation-heures'
      preLoaderRoute: typeof AppValidationHeuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planning': {
      id: '/_app/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AppPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mes-swaps': {
      id: '/_app/mes-swaps'
      path: '/mes-swaps'
      fullPath: '/mes-swaps'
      preLoaderRoute: typeof AppMesSwapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mes-propositions': {
      id: '/_app/mes-propositions'
      path: '/mes-propositions'
      fullPath: '/mes-propositions'
      preLoaderRoute: typeof AppMesPropositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mes-heures': {
      id: '/_app/mes-heures'
      path: '/mes-heures'
      fullPath: '/mes-heures'
      preLoaderRoute: typeof AppMesHeuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interimaires': {
      id: '/_app/interimaires'
      path: '/interimaires'
      fullPath: '/interimaires'
      preLoaderRoute: typeof AppInterimairesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flotte': {
      id: '/_app/flotte'
      path: '/flotte'
      fullPath: '/flotte'
      preLoaderRoute: typeof AppFlotteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employes': {
      id: '/_app/employes'
      path: '/employes'
      fullPath: '/employes'
      preLoaderRoute: typeof AppEmployesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard-employe': {
      id: '/_app/dashboard-employe'
      path: '/dashboard-employe'
      fullPath: '/dashboard-employe'
      preLoaderRoute: typeof AppDashboardEmployeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/absences': {
      id: '/_app/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AppAbsencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devis/': {
      id: '/_app/devis/'
      path: '/devis'
      fullPath: '/devis/'
      preLoaderRoute: typeof AppDevisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires/': {
      id: '/_app/affaires/'
      path: '/affaires'
      fullPath: '/affaires/'
      preLoaderRoute: typeof AppAffairesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres/utilisateurs': {
      id: '/_app/parametres/utilisateurs'
      path: '/parametres/utilisateurs'
      fullPath: '/parametres/utilisateurs'
      preLoaderRoute: typeof AppParametresUtilisateursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres/metiers': {
      id: '/_app/parametres/metiers'
      path: '/parametres/metiers'
      fullPath: '/parametres/metiers'
      preLoaderRoute: typeof AppParametresMetiersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export/demandes-devis': {
      id: '/_app/export/demandes-devis'
      path: '/demandes-devis'
      fullPath: '/export/demandes-devis'
      preLoaderRoute: typeof AppExportDemandesDevisRouteImport
      parentRoute: typeof AppExportRoute
    }
    '/_app/employes/import': {
      id: '/_app/employes/import'
      path: '/import'
      fullPath: '/employes/import'
      preLoaderRoute: typeof AppEmployesImportRouteImport
      parentRoute: typeof AppEmployesRoute
    }
    '/_app/devis/import': {
      id: '/_app/devis/import'
      path: '/devis/import'
      fullPath: '/devis/import'
      preLoaderRoute: typeof AppDevisImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devis/historique': {
      id: '/_app/devis/historique'
      path: '/devis/historique'
      fullPath: '/devis/historique'
      preLoaderRoute: typeof AppDevisHistoriqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires/$affaireId': {
      id: '/_app/affaires/$affaireId'
      path: '/affaires/$affaireId'
      fullPath: '/affaires/$affaireId'
      preLoaderRoute: typeof AppAffairesAffaireIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires/$affaireId/': {
      id: '/_app/affaires/$affaireId/'
      path: '/'
      fullPath: '/affaires/$affaireId/'
      preLoaderRoute: typeof AppAffairesAffaireIdIndexRouteImport
      parentRoute: typeof AppAffairesAffaireIdRoute
    }
    '/_app/affaires/$affaireId/staffing': {
      id: '/_app/affaires/$affaireId/staffing'
      path: '/staffing'
      fullPath: '/affaires/$affaireId/staffing'
      preLoaderRoute: typeof AppAffairesAffaireIdStaffingRouteImport
      parentRoute: typeof AppAffairesAffaireIdRoute
    }
    '/_app/affaires/$affaireId/journal': {
      id: '/_app/affaires/$affaireId/journal'
      path: '/journal'
      fullPath: '/affaires/$affaireId/journal'
      preLoaderRoute: typeof AppAffairesAffaireIdJournalRouteImport
      parentRoute: typeof AppAffairesAffaireIdRoute
    }
    '/_app/affaires/$affaireId/devis': {
      id: '/_app/affaires/$affaireId/devis'
      path: '/devis'
      fullPath: '/affaires/$affaireId/devis'
      preLoaderRoute: typeof AppAffairesAffaireIdDevisRouteImport
      parentRoute: typeof AppAffairesAffaireIdRoute
    }
  }
}

interface AppEmployesRouteChildren {
  AppEmployesImportRoute: typeof AppEmployesImportRoute
}

const AppEmployesRouteChildren: AppEmployesRouteChildren = {
  AppEmployesImportRoute: AppEmployesImportRoute,
}

const AppEmployesRouteWithChildren = AppEmployesRoute._addFileChildren(
  AppEmployesRouteChildren,
)

interface AppExportRouteChildren {
  AppExportDemandesDevisRoute: typeof AppExportDemandesDevisRoute
}

const AppExportRouteChildren: AppExportRouteChildren = {
  AppExportDemandesDevisRoute: AppExportDemandesDevisRoute,
}

const AppExportRouteWithChildren = AppExportRoute._addFileChildren(
  AppExportRouteChildren,
)

interface AppAffairesAffaireIdRouteChildren {
  AppAffairesAffaireIdDevisRoute: typeof AppAffairesAffaireIdDevisRoute
  AppAffairesAffaireIdJournalRoute: typeof AppAffairesAffaireIdJournalRoute
  AppAffairesAffaireIdStaffingRoute: typeof AppAffairesAffaireIdStaffingRoute
  AppAffairesAffaireIdIndexRoute: typeof AppAffairesAffaireIdIndexRoute
}

const AppAffairesAffaireIdRouteChildren: AppAffairesAffaireIdRouteChildren = {
  AppAffairesAffaireIdDevisRoute: AppAffairesAffaireIdDevisRoute,
  AppAffairesAffaireIdJournalRoute: AppAffairesAffaireIdJournalRoute,
  AppAffairesAffaireIdStaffingRoute: AppAffairesAffaireIdStaffingRoute,
  AppAffairesAffaireIdIndexRoute: AppAffairesAffaireIdIndexRoute,
}

const AppAffairesAffaireIdRouteWithChildren =
  AppAffairesAffaireIdRoute._addFileChildren(AppAffairesAffaireIdRouteChildren)

interface AppRouteChildren {
  AppAbsencesRoute: typeof AppAbsencesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDashboardEmployeRoute: typeof AppDashboardEmployeRoute
  AppEmployesRoute: typeof AppEmployesRouteWithChildren
  AppExportRoute: typeof AppExportRouteWithChildren
  AppFlotteRoute: typeof AppFlotteRoute
  AppInterimairesRoute: typeof AppInterimairesRoute
  AppMesHeuresRoute: typeof AppMesHeuresRoute
  AppMesPropositionsRoute: typeof AppMesPropositionsRoute
  AppMesSwapsRoute: typeof AppMesSwapsRoute
  AppPlanningRoute: typeof AppPlanningRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppValidationHeuresRoute: typeof AppValidationHeuresRoute
  AppAffairesAffaireIdRoute: typeof AppAffairesAffaireIdRouteWithChildren
  AppDevisHistoriqueRoute: typeof AppDevisHistoriqueRoute
  AppDevisImportRoute: typeof AppDevisImportRoute
  AppParametresMetiersRoute: typeof AppParametresMetiersRoute
  AppParametresUtilisateursRoute: typeof AppParametresUtilisateursRoute
  AppAffairesIndexRoute: typeof AppAffairesIndexRoute
  AppDevisIndexRoute: typeof AppDevisIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAbsencesRoute: AppAbsencesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDashboardEmployeRoute: AppDashboardEmployeRoute,
  AppEmployesRoute: AppEmployesRouteWithChildren,
  AppExportRoute: AppExportRouteWithChildren,
  AppFlotteRoute: AppFlotteRoute,
  AppInterimairesRoute: AppInterimairesRoute,
  AppMesHeuresRoute: AppMesHeuresRoute,
  AppMesPropositionsRoute: AppMesPropositionsRoute,
  AppMesSwapsRoute: AppMesSwapsRoute,
  AppPlanningRoute: AppPlanningRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppValidationHeuresRoute: AppValidationHeuresRoute,
  AppAffairesAffaireIdRoute: AppAffairesAffaireIdRouteWithChildren,
  AppDevisHistoriqueRoute: AppDevisHistoriqueRoute,
  AppDevisImportRoute: AppDevisImportRoute,
  AppParametresMetiersRoute: AppParametresMetiersRoute,
  AppParametresUtilisateursRoute: AppParametresUtilisateursRoute,
  AppAffairesIndexRoute: AppAffairesIndexRoute,
  AppDevisIndexRoute: AppDevisIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MobileAbsencesRoute: MobileAbsencesRoute,
  MobileAujourdhuiRoute: MobileAujourdhuiRoute,
  MobileHeuresRoute: MobileHeuresRoute,
  MobileMoisRoute: MobileMoisRoute,
  MobileProfilRoute: MobileProfilRoute,
  MobilePropositionsRoute: MobilePropositionsRoute,
  MobileSwapsRoute: MobileSwapsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
