WITH src(numero, client_v, date_opp, taille_v, statut_v, dm, dd, comm) AS (VALUES
('9066', 'GAS BIJOU MEUBLE', '2026-01-16'::date, 'gros'::opportunite_taille, 'envoye'::opportunite_statut, '2026-02-23'::date, NULL::date, NULL),
('9068', 'DEVIS HERMES PHOTOBOOTH', NULL, 'moyen'::opportunite_taille, 'gagne'::opportunite_statut, '2026-02-04'::date, '2026-02-05'::date, 'Envoyé'),
('9069', 'MAXIM ''S place vendome', NULL, 'gros'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9070', 'BFM/RMC', NULL, 'gros'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9071', 'NRJ', NULL, 'tres_gros'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9072', 'Bon marché barrière complémentaire', NULL, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9073', 'GEP devis samy', NULL, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9074', 'BOITE NOIR BIBLIOTHEQUE FRANCOIS MITTERAND', NULL, 'moyen'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9075', 'Crazy Horse', NULL, 'gros'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9076', 'agence panenka - marelle', '2026-01-20'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9077', 'Soirée du club audiovisuel', NULL, 'tres_petit'::opportunite_taille, 'gagne'::opportunite_statut, '2026-02-09'::date, '2026-02-11'::date, NULL),
('9078', 'OOPERCAST pub sport', '2025-12-22'::date, 'moyen'::opportunite_taille, 'gagne'::opportunite_statut, '2026-02-07'::date, NULL, NULL),
('9079', 'PROJET OVOIDE 2026', '2026-01-21'::date, 'gros'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9080', 'PANENKA_CHARIOT', '2026-01-08'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, '2026-04-17'::date, NULL, NULL),
('9081', 'Scene bein', '2026-01-22'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9082', 'Asterios spectacle', '2026-01-26'::date, 'moyen'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9083', 'Anna Armelin', '2026-01-27'::date, 'petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, 'Demande de sous traitance réalisée'),
('9084', 'Stockage oopercast pub sport', NULL, 'tres_petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9085', 'Etude plans plateau bellemare canal', NULL, 'petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9086', 'Elections TF1', NULL, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, 'desk à check à PECQUEUSE MERCREDI + refection le cas échéant - > livraison vendredi 13/02'),
('9087', 'Le répondeur Live', '2026-01-28'::date, 'petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, 'Chaine musicale studio paris - format scénique - cabine téléphonique'),
('9088', 'La samaritaine carte postale été 2026', '2026-01-28'::date, 'gros'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, 'chiffrage à rendre le 11/02, visite technique le 3 février 26'),
('9089', 'prototype G2V', NULL, 'moyen'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9094', 'Shangri la Airplay', '2026-01-29'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9091', 'destruction des decors bangumi', '2026-01-29'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9092', 'Carrousel décoratif - marine bumb', '2026-02-02'::date, 'moyen'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9093', 'Agence auditorium grand palais mediawan', '2026-01-24'::date, 'tres_gros'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9090', 'Hermes VF', '2026-01-28'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, '2026-04-30'::date, NULL, '3 Panonceaux'),
('9095', 'Delicious agency', '2026-01-27'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9096', 'Exposition artiste G2', '2026-02-02'::date, 'gros'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9097', 'CFC Canal one', '2026-02-04'::date, 'tres_gros'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, NULL),
('9098', 'pupitre quizmaster', '2026-02-07'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9099', 'LV chocolat show Paques 2026', '2026-02-08'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, '2026-03-28'::date, NULL, NULL),
('9100', 'LV chocolat show fête des meres 2026', '2026-02-09'::date, 'moyen'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9101', 'Marie Garnier  revele experience', '2026-02-09'::date, 'petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9102', 'Tringle cintre G2v', '2026-02-10'::date, 'moyen'::opportunite_taille, 'envoye'::opportunite_statut, '2026-03-06'::date, NULL, NULL),
('9103', 'Nina paloma expo artiste façade', '2026-02-09'::date, 'moyen'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9104', 'Location pupitre TF1', '2026-02-11'::date, 'tres_petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9105', 'petite table l''equipe21', '2026-02-11'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9106', 'G2V - enseignes sushi park', '2026-02-13'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9107', 'Bein adhesif', '2026-02-13'::date, 'tres_petit'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, NULL),
('9108', 'Chiffrage la villette echelles métallerie', '2026-02-06'::date, 'tres_petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9109', 'Soirée canap mars 26 bangumi', '2026-02-16'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9110', 'elections municipales jean jacques bourdin', NULL, 'petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9111', 'changement de toile enibas 20/03', NULL, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9112', 'total energie tour de france', '2026-02-24'::date, 'moyen'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9113', 'appel a temoins', '2026-05-26'::date, 'moyen'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, NULL),
('9114', 'QP1C', '2026-03-18'::date, 'moyen'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9115', 'Incroyable Talent', '2026-07-01'::date, NULL, 'a_faire'::opportunite_statut, NULL, NULL, NULL),
('9116', 'Restaurant milan mobilier clube', NULL, NULL, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9117', 'Atelier des lumières', NULL, NULL, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9118', 'Demande sie internet SLM Architectes martinique', NULL, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9119', 'Chiffrage gradins tarata', '2026-03-03'::date, 'tres_gros'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9120', 'demenagement en aparté', NULL, NULL, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9121', 'projet atelier PAF robot IA', '2026-02-25'::date, 'gros'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9122', 'Boites untable', NULL, NULL, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9123', 'chouette fluo', '2026-03-02'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9124', 'G2V-cornières patinées', '2026-03-02'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9125', 'IVS-recouvrementdeco', '2026-03-04'::date, 'tres_petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9126', 'G2V - garde-corps + 3D', '2026-03-04'::date, 'moyen'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL)
)
UPDATE affaires a SET
  client = src.client_v,
  date_opportunite = COALESCE(src.date_opp, a.date_opportunite),
  taille = COALESCE(src.taille_v, a.taille),
  statut_opportunite = COALESCE(src.statut_v, a.statut_opportunite),
  date_montage = COALESCE(src.dm, a.date_montage),
  date_demontage = COALESCE(src.dd, a.date_demontage),
  notes = COALESCE(src.comm, a.notes)
FROM src WHERE a.numero = src.numero AND a.phase = 'opportunite';