WITH src(numero, client_v, date_opp, taille_v, statut_v, dm, dd, comm) AS (VALUES
('9190', 'Lancelot demay we love green', '2026-03-31'::date, NULL, 'termine'::opportunite_statut, NULL::date, NULL::date, NULL),
('9191', 'Qui a la solution? Effervescence prod', '2026-04-02'::date, NULL, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9192', 'we love green benne jaune', '2026-04-02'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9193', 'Mairie Impression patrick', '2026-04-03'::date, NULL, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9194', 'Auvent la grande epicérie', '2026-04-09'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9195', 'G2v-projet experience', '2026-04-10'::date, 'gros'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9196', 'Soklap-podcast', '2026-04-14'::date, 'moyen'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9197', 'Remise en peinture boudoir hermes', '2026-04-15'::date, 'tres_petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9198', 'JAPAN EXPO WARNING UP', '2026-04-17'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9199', 'Loges FTV RG 26', '2026-03-01'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9200', 'Montage Démontage vitrine Paris -> Monaco', '2026-04-16'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9201', 'Studio UNESCO', '2026-04-17'::date, 'moyen'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9202', 'Chapiteau cirque La vilette', '2026-04-17'::date, NULL, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9203', 'Rack à chassis décors la villette', '2026-04-17'::date, NULL, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9204', 'YY stand galerie lafayette', '2026-04-17'::date, NULL, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9205', 'Stand Inée - emilien serret', '2026-04-20'::date, 'gros'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9206', 'Products display Jackery WARNING UP', '2026-04-17'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9207', 'The ring La réunion', '2026-04-20'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9208', 'The ring devis type', '2026-04-20'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9209', 'The week end  PUZL', '2026-04-22'::date, 'moyen'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9210', 'BEIN grille', '2026-04-22'::date, 'tres_petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9211', 'BEIN  Support table x4', '2026-04-22'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9212', 'BEIN support cam', '2026-04-22'::date, 'tres_petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9213', 'BEIN deplacement ecran + Fixation', '2026-04-22'::date, 'tres_petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9214', 'BEIN claustra', '2026-04-22'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9215', 'BEIN mur ecran fab + demontage', '2026-04-22'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9216', 'BEIN table de maquillage', '2026-04-22'::date, 'moyen'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9217', 'BEIN Mini cuisine', '2026-04-22'::date, 'moyen'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9218', 'Haus Labs PUZL', '2026-04-22'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9219', 'FLab speciale César sept', '2026-04-22'::date, 'petit'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, NULL),
('9220', 'Arche YSL brumatrice PUZL', '2026-04-23'::date, 'moyen'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, NULL),
('9221', 'cabine intimiste PUZL', '2026-04-27'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9222', 'Tradesk stage scene', '2026-04-26'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9223', 'kermesse louis vuitton chocolat show', '2026-04-20'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9224', 'Maison skorpios site wix', '2026-04-28'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9225', 'CEA victor !', '2026-04-28'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9226', 'It facto toile noire', '2026-04-28'::date, 'tres_petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9227', 'japan expo warnin', '2026-04-28'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9228', 'Lou BECKER WE ARE ONA', '2026-04-29'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9229', 'Mina Dugrillon  BIZ PROD', '2026-04-29'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9230', 'Panenka Tour de france Decathlon', '2026-04-29'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9231', 'Atelier mandarine M&Ms', '2026-04-29'::date, 'tres_petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9232', 'La fabrik totem', '2026-04-25'::date, 'tres_petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9233', 'LaFabrik-hegoa', '2026-04-30'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9234', '13th maker JUNE', '2026-04-30'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9235', 'Le bon marché septembre japan', '2026-04-30'::date, 'tres_gros'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL)
)
UPDATE affaires a SET
  client = src.client_v,
  date_opportunite = COALESCE(src.date_opp, a.date_opportunite),
  taille = COALESCE(src.taille_v, a.taille),
  statut_opportunite = COALESCE(src.statut_v, a.statut_opportunite),
  date_montage = COALESCE(src.dm, a.date_montage),
  date_demontage = COALESCE(src.dd, a.date_demontage),
  notes = COALESCE(src.comm, a.notes)
FROM src WHERE a.numero = src.numero AND a.phase = 'opportunite';