WITH src(numero, client_v, date_opp, taille_v, statut_v, dm, dd, comm) AS (VALUES
('9127', 'Hermes table maquillage', '2026-03-07'::date, 'petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL::date, NULL::date, NULL),
('9128', 'JDME', '2026-04-16'::date, 'moyen'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9129', 'L''evenement France tv iran', '2026-03-07'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9130', 'Awda production', '2026-03-09'::date, NULL, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9131', 'Kheops', '2026-03-09'::date, NULL, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9132', 'BB agency trash machine casino', '2026-03-06'::date, NULL, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9133', 'TV tahiti', '2026-03-05'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9134', 'L''aventure Beaumarly', '2026-02-27'::date, NULL, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9135', 'Qui restera dans la lumieère', '2026-03-10'::date, 'gros'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9136', 'soklap', '2026-01-15'::date, 'gros'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, NULL),
('9137', 'journal du hard', '2026-02-28'::date, 'moyen'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9138', 'bylg ugg', '2026-03-05'::date, NULL, 'perdu'::opportunite_statut, '2026-04-09'::date, '2026-04-09'::date, 'rdv client le 13/03'),
('9139', 'Mise en peinture meubles le bon marché', NULL, NULL, 'termine'::opportunite_statut, NULL, NULL, 'rdv d''info le 16/03 - plans à transmettre'),
('9142', 'Building table football', '2026-03-10'::date, NULL, 'envoye'::opportunite_statut, '2026-04-27'::date, NULL, NULL),
('9143', 'The ring journée presse Honda', '2026-03-01'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9144', 'The ring salon de l''auto hobscotch', NULL, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9145', 'Satto (The ring) - Prototype', '2025-12-18'::date, 'tres_gros'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, 'RDV fait'),
('9146', 'The ring - Salon de l''auto HONDA', '2026-03-01'::date, 'gros'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, NULL),
('9147', 'The ring - Salle Marseille', NULL, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9148', 'The ring - F1 place vendome', NULL, 'gros'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, 'Audi a changé sa date de présentation de la F1 de marsà juin'),
('9149', 'The ring - Evenement SMART PARTY', '2026-09-30'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9150', 'G2V-Schiaparelli', '2026-03-12'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9151', 'Découpe numérique BA Attitude', '2026-03-12'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9152', 'Salle de Projection I NIKA Project Space', '2026-03-11'::date, 'petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, 'non répondu'),
('9153', 'SVR PANENKA jeu du fromage', '2026-03-13'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, '2026-05-18'::date, NULL, 'livraison à définir'),
('9154', 'modif décor en appart', '2026-03-13'::date, 'tres_gros'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9155', 'Panenka roue de la fortune', '2026-03-13'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9156', 'fond vert plateau MERLIN', '2026-03-13'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9157', 'knoll printed wall', '2026-03-13'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9158', 'cyclorama studio 4m 5m', '2026-03-15'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9159', 'Oopercast Juin montage', '2026-06-26'::date, 'petit'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, NULL),
('9160', 'Amazon prime RG', '2026-03-10'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9161', 'Tennis Channel', '2026-03-10'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9162', 'pose moquette France TV', '2026-03-12'::date, NULL, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9163', 'MUXU-mobilier bon marché', '2026-03-19'::date, 'gros'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9164', 'G2V-man ray milan', '2026-03-20'::date, 'gros'::opportunite_taille, 'gagne'::opportunite_statut, '2026-04-16'::date, NULL, NULL),
('9165', 'Fashion week avril 26 - emilien serret', '2026-03-19'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9166', 'Soulac-sur-mer', '2026-03-12'::date, 'tres_gros'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9168', 'Panenka miroirs et meubles', '2026-03-19'::date, NULL, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9169', 'Yonex Roland Garros', '2026-03-18'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9170', 'INCROYABLE TALENT JUILLET 26', '2026-03-21'::date, NULL, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9171', 'Salles de bain UNTABLE GALERIES LAFAYETTE', '2026-03-20'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9172', 'Fashion week bracelets laiton', '2026-03-22'::date, 'moyen'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, 'hors scope - trop difficile'),
('9173', 'Quai d''Orsay', '2026-03-23'::date, 'gros'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9174', 'Table modulaire TDF 2026', '2026-03-24'::date, 'moyen'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9175', 'CFC canal one', '2026-03-24'::date, 'tres_gros'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9176', 'decoupe tole larmée', '2026-03-26'::date, 'petit'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9177', 'Valentine houssin untable -> cotes des roses photocall ° 3 steles + structure disque + porte', '2026-03-26'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9178', 'Lise bourse céréminie d''ouverture', '2026-03-26'::date, NULL, 'a_faire'::opportunite_statut, NULL, NULL, NULL),
('9179', 'Box miroir pour vidéo', '2026-03-26'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9180', 'desperados chd festival - peinture epoxy - remise', '2026-03-26'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, '8000E'),
('9181', 'FRTV-PIDF', '2026-03-27'::date, 'moyen'::opportunite_taille, 'termine'::opportunite_statut, '2026-06-08'::date, NULL, NULL),
('9182', 'dedikazio pavillon royal', '2026-03-30'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9183', 'Folies bergères plateau tournant', '2026-03-31'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9184', 'Alice poubelle - meuble auvent baldoria', '2026-03-31'::date, 'petit'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9185', 'Dibond noir + adhésif', '2026-03-31'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9186', 'G2V-photocall Chanel', '2026-04-01'::date, 'petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9187', 'Lancome agence Puzl', '2026-04-01'::date, 'gros'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9188', 'Tour de France - continental', '2026-04-02'::date, 'moyen'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, NULL),
('9189', 'Samsonite', '2026-04-02'::date, NULL, 'termine'::opportunite_statut, NULL, NULL, NULL)
)
UPDATE affaires a SET
  client = src.client_v,
  date_opportunite = COALESCE(src.date_opp, a.date_opportunite),
  taille = COALESCE(src.taille_v, a.taille),
  statut_opportunite = COALESCE(src.statut_v, a.statut_opportunite),
  date_montage = COALESCE(src.dm, a.date_montage),
  date_demontage = COALESCE(src.dd, a.date_demontage),
  notes = COALESCE(src.comm, a.notes)
FROM src WHERE a.numero = src.numero AND a.phase = 'opportunite';