WITH src(numero, client_v, date_opp, taille_v, statut_v, dm, dd, comm) AS (VALUES
('9026', 'Chargeur', '2025-12-05'::date, 'gros'::opportunite_taille, 'termine'::opportunite_statut, '2026-02-02'::date, NULL::date, 'RDV le 13/01 à 11H'),
('9027', 'Miriban', '2025-12-16'::date, 'gros'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, 'voir avec alex'),
('9028', 'Volontiers', '2025-12-10'::date, 'gros'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, 'Annulé par le client'),
('9029', 'Knoll', '2025-12-04'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9030', 'Thonus (casino)', '2025-11-01'::date, 'moyen'::opportunite_taille, 'perdu'::opportunite_statut, '2026-03-26'::date, NULL, 'Retour le 26/01/2026'),
('9031', 'IT facto', '2025-11-15'::date, 'moyen'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, 'devis à refaire'),
('9032', 'Rebecca', '2025-12-02'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, '2026-01-24'::date, '2026-01-24'::date, 'devis à refaire'),
('9033', 'LV devis dépose noel', '2025-12-02'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, 'terminé'),
('9034', 'Miara', '2025-12-03'::date, 'tres_petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9035', 'Bon marché ferme', '2025-12-08'::date, 'tres_gros'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9036', 'Carla safouret', '2025-12-10'::date, 'moyen'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, 'Non répondu'),
('9037', '1788 l''agence', '2025-12-10'::date, 'moyen'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, 'Non répondu'),
('9038', 'La fabrik', '2025-12-10'::date, 'tres_petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, 'terminé'),
('9039', 'Emera', '2025-12-10'::date, 'gros'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, 'Devis à faire'),
('9040', 'Pauline stern', '2025-12-12'::date, 'petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9042', 'Jean-marie couchy (Tv saint denis)', '2025-11-15'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, 'Non répondu'),
('9043', 'Paroisse saint maur', '2025-11-01'::date, 'petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9044', 'Valentine logo', NULL, 'tres_petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9046', 'Transport la villette', NULL, 'tres_petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9048', 'Piano volant (airpla)', NULL, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, 'Non répondu'),
('9049', 'Flab prod', '2025-12-12'::date, NULL, 'perdu'::opportunite_statut, NULL, NULL, '???'),
('9050', 'Antenne reunion', NULL, 'tres_gros'::opportunite_taille, 'envoye'::opportunite_statut, NULL, NULL, 'En attente d''un go'),
('9051', 'L''équipe table', '2025-12-15'::date, 'petit'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, 'Non répondu'),
('9052', '13th maker machine à laver', '2025-12-16'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, '2026-01-19'::date, '2026-01-26'::date, 'Commande le buffet + miroir avec nadège + stèle location + grille '),
('9053', 'Table sips Unesco', '2025-12-15'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9054', 'Stand poliakov', NULL, 'tres_gros'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, 'Non répondu'),
('9055', 'J''en connais un rayon', '2025-12-17'::date, 'gros'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9056', 'Valentine Houssin (Kering)', '2025-12-17'::date, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, '8 stèles blanc mat en loc + chassis'),
('9057', 'LV Saint valentin ', NULL, 'petit'::opportunite_taille, 'a_faire'::opportunite_statut, '2026-02-02'::date, NULL, 'livraison puzzle (x65) pour le 29/01'),
('9058', 'La boite à question little big paris', '2025-12-31'::date, 'tres_petit'::opportunite_taille, 'perdu'::opportunite_statut, NULL, NULL, NULL),
('9059', 'Tapisserie nouvel an', NULL, 'petit'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9060', 'Démontage the voice', NULL, 'gros'::opportunite_taille, 'termine'::opportunite_statut, NULL, NULL, NULL),
('9061', 'Montage the voice mars 26', '2026-01-08'::date, 'tres_gros'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9062', 'Yonex birmigham', '2026-01-08'::date, 'tres_gros'::opportunite_taille, 'gagne'::opportunite_statut, NULL, NULL, NULL),
('9063', 'Penderie montage/démontage', '2026-01-08'::date, 'petit'::opportunite_taille, 'a_faire'::opportunite_statut, '2026-01-20'::date, '2026-01-20'::date, NULL),
('9064', 'Appel à témoin Janvier 26', '2026-01-08'::date, 'moyen'::opportunite_taille, 'a_faire'::opportunite_statut, NULL, NULL, NULL),
('9065', 'Event le bon marché', '2026-02-11'::date, 'tres_gros'::opportunite_taille, 'a_faire'::opportunite_statut, '2026-02-10'::date, '2026-02-13'::date, 'Théatre bobino')
)
UPDATE affaires a SET
  client = src.client_v,
  date_opportunite = COALESCE(src.date_opp, a.date_opportunite),
  taille = COALESCE(src.taille_v, a.taille),
  statut_opportunite = COALESCE(src.statut_v, a.statut_opportunite),
  date_montage = COALESCE(src.dm, a.date_montage),
  date_demontage = COALESCE(src.dd, a.date_demontage),
  notes = COALESCE(src.comm, a.notes)
FROM src WHERE a.numero = src.numero AND a.phase = 'opportunite';